### ISSUE TITLE
DNS error

### ISSUE THREAD

**Issue by tiangomez** [bplmp/metabase-google-sheets-add-on#1]
@bplmp the script is running; however, I am getting a message saying "DNS error: http://nullapi/card/57/query/csv". Any thoughts?

**Comment by bplmp** [comment]
@tiangomez I haven't seen this type of error before; my guess is that it is related to the DNS of your domain, try checking that perhaps

**Comment by bplmp** [comment]
Wait did you set `BASE_URL` and other variables? https://github.com/bplmp/metabase-google-sheets-add-on#metabase-api-access

**Comment by natea** [comment]
I was getting the same error, and it's because I hadn't set the BASE_URL. In the new Google Script editor, It's not clear from your instructions where one goes to make these ENV settings. I don't see a File->Project Properties.

Once I switched to the legacy script editor, then it was very clear where to go to make these settings changes.

**Comment by bplmp** [comment]
Apparently this is really an issue... https://stackoverflow.com/questions/65740899/how-do-i-view-script-properties-in-the-new-google-apps-script-ide

I think switching to the old editor is what works for now
